import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `coin_market_cap.dart` with the code generated by Freezed
part 'coinmarketcap_models.freezed.dart';
// optional: Since our CoinMarketCap class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'coinmarketcap_models.g.dart';


@freezed
class CoinMarketCap with _$CoinMarketCap {
  const factory CoinMarketCap({
    Data? data,
    Status? status,
  }) = _CoinMarketCap;

  factory CoinMarketCap.fromJson(Map<String, dynamic> json) => _$CoinMarketCapFromJson(json);

  // Map<String, dynamic> toJson() => {
  //       'data': data,
  //       'age': status,
  //     };
}

@freezed
class Data with _$Data {
  const factory Data({
    List<CryptoCurrencyList>? cryptoCurrencyList,
    String? totalCount,
  }) = _Data;

  factory Data.fromJson(Map<String, dynamic> json) => _$DataFromJson(json);

  // Map<String, dynamic> toJson() {
  //   return {'cryptoCurrency': cryptoCurrency, 'totalCount': totalCount};
  // }
}

@freezed
class CryptoCurrencyList with _$CryptoCurrencyList {

  const factory CryptoCurrencyList({
    num? id,
    String? name,
    String? symbol,
    String? slug,
    num? cmcRank,
    num? marketPairCount,
    double? circulatingSupply,
    num? selfReportedCirculatingSupply,
    double? totalSupply,
    // num? maxSupply,
    double? ath,
    double? atl,
    double? high24h,
    double? low24h,
    num? isActive,
    String? lastUpdated,
    String? dateAdded,
    List<Quotes>? quotes,
    bool? isAudited,
  }) = _CryptoCurrencyList;

  factory CryptoCurrencyList.fromJson(Map<String, dynamic> json) => _$CryptoCurrencyListFromJson(json);

  // Map<String, dynamic> toJson() {
  //   return {
  //     'id': id,
  //     'name': name,
  //     'symbol': symbol,
  //     'slug': slug,
  //     'cmcRank': cmcRank,
  //     'marketPairCount': marketPairCount,
  //     'circulatingSupply': circulatingSupply,
  //     'selfReportedCirculatingSupply': selfReportedCirculatingSupply,
  //     'totalSupply': totalSupply,
  //     // 'maxSupply': maxSupply,
  //     'ath': ath,
  //     'atl': atl,
  //     'high24h': high24h,
  //     'low24h': low24h,
  //     'isActive': isActive,
  //     'lastUpdated': lastUpdated,
  //     'dateAdded': dateAdded,
  //     'quotes': quotes,
  //     'isAudited': isAudited,
  //   };
  // }
}

@freezed
class Quotes with _$Quotes {

  const factory Quotes({
    String? name,
    num? price,
    num? volume24h,
    num? volume7d,
    num? volume30d,
    num? marketCap,
    num? selfReportedMarketCap,
    num? percentChange1h,
    num? percentChange24h,
    num? percentChange7d,
    String? lastUpdated,
    num? percentChange30d,
    num? percentChange60d,
    num? percentChange90d,
    num? fullyDilluttedMarketCap,
    num? marketCapByTotalSupply,
    num? dominance,
    num? turnover,
    num? ytdPriceChangePercentage,
  }) = _Quotes;

  factory Quotes.fromJson(Map<String, dynamic> json) => _$QuotesFromJson(json);

  // Map<String, dynamic> toJson() {
  //   return {
  //     'name': name,
  //     'price': price,
  //     'volume24h': volume24h,
  //     'volume7d': volume7d,
  //     'volume30d': volume30d,
  //     'marketCap': marketCap,
  //     'selfReportedMarketCap': selfReportedMarketCap,
  //     'percentChange1h': percentChange1h,
  //     'percentChange24h': percentChange24h,
  //     'percentChange7d': percentChange7d,
  //     'lastUpdated': lastUpdated,
  //     'percentChange30d': percentChange30d,
  //     'percentChange60d': percentChange60d,
  //     'percentChange90d': percentChange90d,
  //     'fullyDilluttedMarketCap': fullyDilluttedMarketCap,
  //     'marketCapByTotalSupply': marketCapByTotalSupply,
  //     'dominance': dominance,
  //     'turnover': turnover,
  //     'ytdPriceChangePercentage': ytdPriceChangePercentage,
  //   };
  // }
}

@freezed
class Status with _$Status {

  const factory Status({
    String? timestamp,
    String? errorCode,
    String? errorMessage,
    String? elapsed,
    num? creditCount,
  }) = _Status;

  factory Status.fromJson(Map<String, dynamic> json) => _$StatusFromJson(json);

  // Map<String, dynamic> toJson() {
  //   return {
  //     'timestamp': timestamp,
  //     'errorCode': errorCode,
  //     'errorMessage': errorMessage,
  //     'elapsed': elapsed,
  //     'creditCount': creditCount,
  //   };
  // }
}
